# Generated by Django 5.0.3 on 2024-08-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='choise',
            field=models.CharField(choices=[('NEWS', 'NW'), ('ARTICLE', 'AR')], default='Статья', max_length=7),
        ),
    ]
