# Generated by Django 5.0.3 on 2024-08-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_post_post_category_alter_post_choise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='datetime',
            new_name='pdatetime',
        ),
        migrations.AlterField(
            model_name='post',
            name='choise',
            field=models.CharField(choices=[('NEWS', 'NW'), ('AR', 'ARTICLE')], default='Статья', max_length=7),
        ),
    ]
