# Generated by Django 5.1 on 2024-08-26 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_datetime_post_pdatetime_alter_post_choise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='choise',
            field=models.CharField(choices=[('NW', 'NEWS'), ('AR', 'ARTICLE')], default='Статья', max_length=7),
        ),
    ]
