# Generated by Django 5.1 on 2024-08-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_subscribers_alter_post_choise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='choise',
            field=models.CharField(choices=[('NEWS', 'NW'), ('AR', 'ARTICLE')], default='Статья', max_length=7),
        ),
    ]
